Repository AY2021S2-CS2113T-T09-1/tp, pull requests merged in 2021-04, with the labels that each got.

#179 Update parser javadocs
  src/main/java/seedu/duke/parser/CheckInParser.java
  src/main/java/seedu/duke/parser/CheckoutParser.java
  src/main/java/seedu/duke/parser/ClearParser.java
  src/main/java/seedu/duke/parser/EditMaxParser.java
  src/main/java/seedu/duke/parser/ExitParser.java
  src/main/java/seedu/duke/parser/FindParser.java
  src/main/java/seedu/duke/parser/HelpParser.java
  src/main/java/seedu/duke/parser/ListAllParser.java
  src/main/java/seedu/duke/parser/ListCheckedInParser.java
  src/main/java/seedu/duke/parser/MoveStorageParser.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: severity.Low, type.Task

#182 Update DG with architecture component
  docs/DeveloperGuide.md
Labels: priority.Low

#231 Fix check out issues
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/CheckoutCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/exceptions/CheckoutException.java
  src/main/java/seedu/duke/parser/CheckoutParser.java
Labels: type.Bug

#234 Change list to listcheckedin
  src/main/java/seedu/duke/commands/ListCheckedInCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/TextUi.java
  src/test/java/seedu/duke/parser/ListCheckedInParserTest.java
Labels: type.Bug

#233 Match help command message with UG command summary
  docs/UserGuide.md
  src/main/java/seedu/duke/common/Messages.java
Labels: type.Bug

#232 Change editmax command error message and removed name for location
  src/main/java/seedu/duke/commands/EditMaxCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/location/Location.java
  src/test/java/seedu/duke/location/LocationTest.java
  src/test/java/seedu/duke/testutil/SampleLocations.java
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: type.Bug

#236 Check if a visitor has already checked in
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/CheckInCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/exceptions/CheckInException.java
Labels: type.Bug

#258 Update non functional requirements and glossary
  docs/DeveloperGuide.md
Labels: type.Task
