Repository AY2021S2-CS2113T-T09-1/tp, pull requests merged in 2021-03, with the labels that each got.

#43 Bug-Fix
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#47 Add assertion in CheckoutCommand class and pass PersonNotFoundException
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/CheckoutCommand.java
  src/main/java/seedu/duke/commands/FindCommand.java
  src/main/java/seedu/duke/person/TrackingList.java
Labels: type.Bug

#49 Added assertions and RegEx in Id, Name and Phone classes.
  build.gradle
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/person/Id.java
  src/main/java/seedu/duke/person/Name.java
  src/main/java/seedu/duke/person/Person.java
  src/main/java/seedu/duke/person/Phone.java
  src/test/java/seedu/duke/testutil/PersonBuilder.java
  src/test/java/seedu/duke/testutil/SamplePersons.java
Labels: type.Bug

#53 add logging and assertion
  src/main/java/seedu/duke/ui/TextUi.java
Labels: type.Bug

#63 Create Location class and other bug fixes
  src/main/java/seedu/duke/commands/CheckoutCommand.java
  src/main/java/seedu/duke/location/Location.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.High, type.Enhancement

#69 Change to UI
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ui/TextUi.java
Labels: priority.Low

#68 JUnit testings for all the command classes
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/CheckoutCommand.java
  src/main/java/seedu/duke/commands/ClearCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/commands/ListCheckedInCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/exceptions/InvalidCommandException.java
  src/main/java/seedu/duke/exceptions/NoArgumentPassedException.java
  src/main/java/seedu/duke/exceptions/PersonNotFoundException.java
  src/main/java/seedu/duke/exceptions/StorageOperationException.java
  src/main/java/seedu/duke/exceptions/WrongFlagException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/person/TrackingList.java
  src/main/java/seedu/duke/storage/StorageFile.java
  src/main/java/seedu/duke/storage/TrackingListDecoder.java
  src/main/java/seedu/duke/ui/TextUi.java
  src/test/java/seedu/duke/commands/CheckInCommandTest.java
  src/test/java/seedu/duke/commands/CheckoutCommandTest.java
  src/test/java/seedu/duke/commands/ClearCommandTest.java
  src/test/java/seedu/duke/commands/FindCommandTest.java
  src/test/java/seedu/duke/testutil/SampleTrackingList.java
Labels: priority.High, type.Bug

#81 Complete LocationTest
  src/main/java/seedu/duke/location/Location.java
  src/test/java/seedu/duke/location/LocationTest.java
  src/test/java/seedu/duke/testutil/LocationBuilder.java
  src/test/java/seedu/duke/testutil/SampleLocations.java
Labels: priority.High, type.Bug

#84 Add UI component and minor touch up on DG
  docs/DeveloperGuide.md
Labels: priority.Low

#85 Update DG with value proposition and user stories
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: priority.Medium, type.Story, type.Task

#76 Add test for phone class
  src/main/java/seedu/duke/person/Person.java
  src/main/java/seedu/duke/person/Phone.java
  src/test/java/seedu/duke/person/PhoneTest.java
Labels: priority.Medium

#92 Added Storage JUnit tests
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/storage/StorageFile.java
  src/test/data/StorageFileTest/InvalidData.txt
  src/test/data/StorageFileTest/ValidData.txt
  src/test/java/seedu/duke/person/TrackingListTest.java
  src/test/java/seedu/duke/storage/StorageFileTest.java
  src/test/java/seedu/duke/testutil/SampleTrackingList.java
Labels: priority.High

#95 Added developer guide for storage
  docs/DeveloperGuide.md
Labels: priority.Medium

#91 Complete EditMaxCommandTest
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/EditMaxCommand.java
  src/test/java/seedu/duke/commands/EditMaxCommandTest.java
  src/test/java/seedu/duke/commands/FindCommandTest.java
Labels: priority.High, type.Bug

#99 Update parser test coverage
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Enhancement

#102 Update UG
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#108 Create HelpCommand and HelpCommandTest
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/test/java/seedu/duke/commands/ExitCommandTest.java
  src/test/java/seedu/duke/commands/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story

#113 Add another constructor for checkin command for returning visitors
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/CheckInCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/person/Id.java
  src/test/java/seedu/duke/commands/CheckInCommandTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: priority.High, type.Enhancement

#121 Remove Location parameter from the constructor
  src/main/java/seedu/duke/commands/EditMaxCommand.java
  src/test/java/seedu/duke/commands/EditMaxCommandTest.java
Labels: priority.High

#126 Add editmax parser, and help parser
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/exceptions/InvalidIntegerException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: priority.Medium, type.Task

#129 Modify logic to obtain location from user
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/CheckInCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/exceptions/InvalidArgumentSizeException.java
  src/main/java/seedu/duke/exceptions/InvalidMaxCapacityException.java
  src/main/java/seedu/duke/location/Location.java
  src/test/java/seedu/duke/location/LocationTest.java
  src/test/java/seedu/duke/testutil/LocationBuilder.java
  src/test/java/seedu/duke/testutil/SampleLocations.java
Labels: priority.High, severity.High, type.Bug

#135 Modify check-in logic and update the affected parts of the code
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/CheckInCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/commands/CheckInCommandTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: priority.High, severity.High

#141 Debug checkin parsing
  docs/UserGuide.md
  src/main/java/seedu/duke/parser/Parser.java
Labels: type.Bug

#139 Update UG
  docs/UserGuide.md
Labels: priority.Low

#147 Implement Date and Time for History
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/CheckInCommand.java
  src/main/java/seedu/duke/commands/CheckoutCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/datetime/DateTime.java
  src/main/java/seedu/duke/history/HistoryFile.java
  src/test/java/seedu/duke/commands/CheckInCommandTest.java
  src/test/java/seedu/duke/commands/CheckoutCommandTest.java
Labels: type.Enhancement
